/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_services_distance_ProteinNativeQScoreDistance */

#ifndef _Included_com_example_services_distance_ProteinNativeQScoreDistance
#define _Included_com_example_services_distance_ProteinNativeQScoreDistance
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_services_distance_ProteinNativeQScoreDistance_serialVersionUID
#define com_example_services_distance_ProteinNativeQScoreDistance_serialVersionUID 124687651462LL
/*
 * Class:     com_example_services_distance_ProteinNativeQScoreDistance
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_services_distance_ProteinNativeQScoreDistance_init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_services_distance_ProteinNativeQScoreDistance
 * Method:    getStats
 * Signature: (Ljava/lang/String;Ljava/lang/String;F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_example_services_distance_ProteinNativeQScoreDistance_getStats
  (JNIEnv *, jclass, jstring, jstring, jfloat);

#ifdef __cplusplus
}
#endif
#endif
