/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class messif_distance_impl_ProteinNativeQScoreDistance */

#ifndef _Included_messif_distance_impl_ProteinNativeQScoreDistance
#define _Included_messif_distance_impl_ProteinNativeQScoreDistance
#ifdef __cplusplus
extern "C" {
#endif
#undef messif_distance_impl_ProteinNativeQScoreDistance_serialVersionUID
#define messif_distance_impl_ProteinNativeQScoreDistance_serialVersionUID 124687651462LL
/*
 * Class:     messif_distance_impl_ProteinNativeQScoreDistance
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;ZD)V
 */
JNIEXPORT void JNICALL Java_messif_distance_impl_ProteinNativeQScoreDistance_init
  (JNIEnv *, jclass, jstring, jstring, jboolean, jdouble);

/*
 * Class:     messif_distance_impl_ProteinNativeQScoreDistance
 * Method:    getNativeDistance
 * Signature: (Ljava/lang/String;Ljava/lang/String;FZ)F
 */
JNIEXPORT jfloat JNICALL Java_messif_distance_impl_ProteinNativeQScoreDistance_getNativeDistance
  (JNIEnv *, jobject, jstring, jstring, jfloat, jboolean);

#ifdef __cplusplus
}
#endif
#endif
