/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class messif_distance_impl_ProteinNativeQScoreDistance */

#ifndef _Included_messif_distance_impl_ProteinNativeQScoreDistance
#define _Included_messif_distance_impl_ProteinNativeQScoreDistance
#ifdef __cplusplus
extern "C" {
#endif
#undef messif_distance_impl_ProteinNativeQScoreDistance_serialVersionUID
#define messif_distance_impl_ProteinNativeQScoreDistance_serialVersionUID 124687651462LL
/*
 * Class:     messif_distance_impl_ProteinNativeQScoreDistance
 * Method:    init
 * Signature: (Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_messif_distance_impl_ProteinNativeQScoreDistance_init
  (JNIEnv *, jclass, jstring, jdouble);

/*
 * Class:     messif_distance_impl_ProteinNativeQScoreDistance
 * Method:    getStats
 * Signature: (Ljava/lang/String;Ljava/lang/String;F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_messif_distance_impl_ProteinNativeQScoreDistance_getStats
  (JNIEnv *, jclass, jstring, jstring, jfloat);

#ifdef __cplusplus
}
#endif
#endif
