/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ProteinDistance */

#ifndef _Included_ProteinDistance
#define _Included_ProteinDistance
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ProteinDistance
 * Method:    getDistance
 * Signature: (Ljava/lang/String;Ljava/lang/String;F)F
 */
JNIEXPORT jfloat JNICALL Java_ProteinDistance_getDistance
  (JNIEnv *, jobject, jstring, jstring, jfloat);

/*
 * Class:     ProteinDistance
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;ZD)V
 */
JNIEXPORT void JNICALL Java_ProteinDistance_init
  (JNIEnv *, jobject, jstring, jstring, jboolean, jdouble);

#ifdef __cplusplus
}
#endif
#endif
